name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: codeql-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  Go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with: { go-version: v1.25.5, cache: true }
      - run: go fmt ./...
      - run: go mod download
      - run: go mod verify
      - { run: du -sh $(find docs -type f) | sort -h, shell: bash }
      - { run: du -sh docs, shell: bash }
      - run: go test -cpuprofile cpu.pprof -memprofile mem.pprof -race -timeout 300s -v -count=1 -run ^TestBuilder_docsSiteAllocationScaling$ go.ufukty.com/kask/internal/builder
        shell: bash
      - uses: actions/upload-artifact@v6
        with:
          name: cpu.pprof
          path: cpu.pprof
      - uses: actions/upload-artifact@v6
        with:
          name: mem.pprof
          path: mem.pprof
      - run: go mod tidy; git diff --exit-code go.mod go.sum
      - uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9
      - run: go test -race -v -timeout 600s ./...
      - uses: ufukty/golistics@v0.3.1
